version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # Actor Backend service dependencies
  - package-ecosystem: "npm"
    directory: "/backend/actor-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # Movie Backend service dependencies
  - package-ecosystem: "npm"
    directory: "/backend/movie-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # Review Backend service dependencies
  - package-ecosystem: "npm"
    directory: "/backend/review-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # Scene Backend service dependencies
  - package-ecosystem: "npm"
    directory: "/backend/scene-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # User Backend service dependencies
  - package-ecosystem: "npm"
    directory: "/backend/user-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    assignees:
      - "@me"
    reviewers:
      - "@me"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    assignees:
      - "@me"
    reviewers:
      - "@me"
