name: Bug Report
description: Create a bug report to help us improve Cinecom
title: "[Bug] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: component
    attributes:
      label: Component/Service
      description: Which part of the Cinecom application is affected?
      placeholder: "e.g., Frontend, User Service, Movie Service, Authentication"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Environment where the bug occurred
      placeholder: "e.g., Development, Staging, Production"
    validations:
      required: true

  - type: textarea
    id: browser-os
    attributes:
      label: Browser/OS Information (if applicable)
      description: Browser and OS information if this is a frontend issue
      placeholder: "e.g., Chrome 118, macOS 14, Safari 17"

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs/Screenshots
      description: If applicable, add screenshots or error logs to help explain your problem
      placeholder: Paste error logs here or attach screenshots

  - type: checkboxes
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - label: Critical - Blocks core functionality
        - label: High - Significantly impacts user experience
        - label: Medium - Minor impact on functionality
        - label: Low - Cosmetic or minor issue

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...